package shoppingappjavafx.usecase;

import shoppingappjavafx.usecaserealization.predicate.AtLeastOneProductInCart;
import shoppingappjavafx.usecaserealization.predicate.LessThan10Products;
import shoppingappjavafx.usecaserealization.systemreaction.AddProductToPurchaseOrder;
import shoppingappjavafx.usecaserealization.systemreaction.DisplayPaymentDetailsForm;
import shoppingappjavafx.usecaserealization.systemreaction.DisplayProducts;
import shoppingappjavafx.usecaserealization.systemreaction.DisplayPurchaseOrderSummary;
import shoppingappjavafx.usecaserealization.systemreaction.DisplayShippingInformationForm;
import shoppingappjavafx.usecaserealization.systemreaction.InitiateShipping;
import shoppingappjavafx.usecaserealization.systemreaction.SavePaymentDetails;
import shoppingappjavafx.usecaserealization.systemreaction.SaveShippingInformation;
import shoppingappjavafx.usecaserealization.systemreaction.StartWithEmptyShoppingCart;

public interface BuyProductRealization {
	StartWithEmptyShoppingCart startWithEmptyShoppingCart();
	DisplayProducts displayProducts();
	AddProductToPurchaseOrder addProductToPurchaseOrder();
	LessThan10Products lessThan10Products();
	DisplayShippingInformationForm displayShippingInformationForm();
	SaveShippingInformation saveShippingInformation();
	DisplayPaymentDetailsForm displayPaymentDetailsForm();
	SavePaymentDetails savePaymentDetails();
	DisplayPurchaseOrderSummary displayPurchaseOrderSummary();
	InitiateShipping initiateShipping(); 
	AtLeastOneProductInCart atLeastOneProductInCart();
	InformUserAndLogException informUserAndLogException();
}
